# Generated by Django 6.0.4 on 2026-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pet_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lastSignedIn',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='loginMethod',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='openId',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('tutor', 'Tutor')], default='tutor', max_length=20),
        ),
    ]
