# Generated by Django 6.0.4 on 2026-05-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_lastsignedin_customuser_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='defaultQuantity',
            field=models.IntegerField(default=50, help_text='Quantidade padrão em gramas'),
        ),
    ]
