# Generated by Django 6.0.4 on 2026-05-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='dispenser_channel',
            field=models.IntegerField(blank=True, choices=[(1, 'Reservatório 1'), (2, 'Reservatório 2'), (3, 'Reservatório 3'), (4, 'Reservatório 4'), (5, 'Reservatório 5')], help_text='Canal do servo/dispensador (1-5) associado a este pet', null=True),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(condition=models.Q(('dispenser_channel', None), _negated=True), fields=('user', 'dispenser_channel'), name='unique_dispenser_channel_per_user'),
        ),
    ]
