# Generated by Django 6.0.4 on 2026-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pet_dispenser_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.CharField(blank=True, help_text='UF - Ex: SP, RJ, MG', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone com DDD', max_length=20, null=True),
        ),
    ]
