# Generated by Django 6.0.4 on 2026-07-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_cidade_customuser_cpf_customuser_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='channel',
            field=models.IntegerField(blank=True, choices=[(0, 'Dispensador 1'), (1, 'Dispensador 2'), (2, 'Dispensador 3'), (3, 'Dispensador 4'), (4, 'Dispensador 5')], help_text='Canal/dispositivo específico (0-4)', null=True),
        ),
        migrations.AddConstraint(
            model_name='devicestatus',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='unique_device_channel_per_user'),
        ),
    ]
