# Generated by Django 6.0.4 on 2026-08-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_devicestatus_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='dispenserCleaningReminderDays',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='emailDispenserCleaning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='lastDispenserCleaningReminderAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='pushDispenserCleaning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('feeding_completed', 'Feeding Completed'), ('low_food', 'Low Food'), ('device_offline', 'Device Offline'), ('dispenser_cleaning', 'Dispenser Cleaning'), ('general', 'General')], max_length=30),
        ),
    ]
